version: '3'
name: ingrytech
services:
  ingrytech:
    image: golang:1.22
    entrypoint: bash -c "go install -buildvcs=false ./cmd/ingrytech && ./bin/ingrytech"
    working_dir: /ingrytech
    ports:
      - 8085:8085
    volumes:
      - ..:/ingrytech
    environment:
      GOPATH: /ingrytech
      GO111MODULE: auto
      CONFIG_PATH: ./configs/local.yaml
    
  migrate-up:
    image: jerray/goose:2.7.0-rc3
    entrypoint: goose -dir=/migrations postgres postgres://postgres:postgres@postgres-dev:5432/postgres?sslmode=disable up
    volumes:
      - ../build/migrations:/migrations

  migrate-down:
    image: jerray/goose:2.7.0-rc3
    entrypoint: goose -dir=/migrations postgres postgres://postgres:postgres@postgres-dev:5432/postgres?sslmode=disable down-to 0
    volumes:
      - ../build/migrations:/migrations

networks:
  default:
    name: tat-network
    external: true